---
grails:
    profile: web
    codegen:
        defaultPackage: testgrails12
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: com.mysql.jdbc.Driver
    username: ggloor@ggloor
    password: rtnxeg10121996*

environments:
    development:
        dataSource:
            dbCreate: update
            url: jdbc:mysql://ggloor.mysql.database.azure.com:3306/ggloor?useSSL=true&requireSSL=false&autoReconnect=true
    test:
        dataSource:
            dbCreate: create-drop
            url: jdbc:mysql://ggloor.mysql.database.azure.com:3306/ggloor?useSSL=true&requireSSL=false&autoReconnect=true
    production:
        dataSource:
            dbCreate: update
            url: jdbc:mysql://ggloor.mysql.database.azure.com:3306/ggloor?useSSL=true&requireSSL=false&autoReconnect=true
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

#
#grails:
#    plugin:
#        springsecurity:
#            oauth2:
#                providers:
#                    google:
#                        api_key: 'google-api-key'               #needed
#                        api_secret: 'google-api-secret'         #needed
#                        successUri: "/oauth2/google/success"    #optional
#                        failureUri: "/oauth2/google/failure"    #optional
#                        callback: "/oauth2/google/callback"     #optional
#                        scopes: "some_scope"                    #optional, see https://developers.google.com/identity/protocols/googlescopes#monitoringv3

grails:
   mail:
      host: smtp.yandex.ru
      port: 465
      username: noreply@bitloor.com
      password: rtnxeg1012
      props: ['mail.smtp.starttls.enable': 'true',
                           'mail.smtp.port': '465']

